-- SOLUCIÓN INTEGRAL PARA MOVIMIENTOS Y RELACIONES
-- Ejecuta este script en el SQL Editor de Supabase.

-- 1. Asegurar que la tabla existe con los campos correctos
CREATE TABLE IF NOT EXISTS public.app_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    category TEXT NOT NULL,
    action TEXT NOT NULL,
    description TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb
);

-- 2. Agregar Relaciones (Foreign Keys) para que aparezcan en el ER Diagram
ALTER TABLE public.app_movements 
ADD COLUMN IF NOT EXISTS stock_item_id BIGINT REFERENCES public.stock_items(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS transaction_id BIGINT REFERENCES public.transactions(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS sale_id BIGINT REFERENCES public.sales(id) ON DELETE SET NULL;

-- 3. Habilitar RLS (Row Level Security) y crear política de acceso
-- Esto soluciona que la tabla aparezca vacía si el RLS estaba activo sin políticas.
ALTER TABLE public.app_movements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable access to all users" ON "public"."app_movements";
CREATE POLICY "Enable access to all users" ON "public"."app_movements" FOR ALL USING (true);

-- 4. Índices para rendimiento
CREATE INDEX IF NOT EXISTS idx_movements_stock_item ON public.app_movements(stock_item_id);
CREATE INDEX IF NOT EXISTS idx_movements_transaction ON public.app_movements(transaction_id);
CREATE INDEX IF NOT EXISTS idx_movements_sale ON public.app_movements(sale_id);

-- 5. Comentario para Supabase
COMMENT ON TABLE app_movements IS 'Registro de actividad y trazabilidad con relaciones vinculadas';
