-- TABLA PARA MULTI-FORMATOS DE PACKS
CREATE TABLE IF NOT EXISTS public.stock_item_formats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    stock_item_id BIGINT REFERENCES public.stock_items(id) ON DELETE CASCADE,
    pack_size DOUBLE PRECISION NOT NULL, -- Cantidad de unidades (ej. 6, 10, 12, 24)
    pack_price DOUBLE PRECISION NOT NULL, -- Precio de venta sugerido para este formato
    label TEXT -- Etiqueta opcional (ej. "Pack x6", "Cajón", "Media Docena")
);

-- RLS (Row Level Security)
ALTER TABLE public.stock_item_formats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable access to all users" ON "public"."stock_item_formats" FOR ALL USING (true);

-- Indices para búsqueda rápida
CREATE INDEX idx_stock_item_formats_item_id ON public.stock_item_formats(stock_item_id);
